using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace DiscoDialogSimulator.DialogueSystem
{
	public enum SkillType
	{
		NONE,
		LOGIC,
		ENCYCLOPEDIA,
		RHETORIC,
		DRAMA,
		CONCEPTUALIZATION,
		VISUAL_CALCULUS,
		VOLITION,
		INLAND_EMPIRE,
		EMPATHY,
		AUTHORITY,
		SUGGESTION,
		ESPRIT_DE_CORPS,
		PHYSICAL_INSTRUMENT,
		ELECTROCHEMISTRY,
		ENDURANCE,
		CONVALESCENCE,
		HALF_LIGHT,
		PAIN_THRESHOLD,
		SHIVERS,
		HE_COORDINATION,
		PERCEPTION,
		HEARING,
		SIGHT,
		SMELL,
		TASTE,
		REACTION,
		SAVOIR_FAIRE,
		INTERFACING,
		COMPOSURE,
		ALT
	}
}
